import tempfile
import unittest
from pathlib import Path

import trimesh

from fdm_slicer import SliceSettings, slice_mesh_to_gcode


class PipelineTest(unittest.TestCase):
    def test_generates_gcode_with_layers(self) -> None:
        mesh = trimesh.creation.cylinder(radius=8.0, height=20.0, sections=64)
        with tempfile.TemporaryDirectory() as tmpdir:
            mesh_path = Path(tmpdir) / "cylinder.stl"
            out_path = Path(tmpdir) / "cylinder.gcode"
            mesh.export(mesh_path)
            slice_mesh_to_gcode(mesh_path, out_path, SliceSettings(layer_height=0.4))
            content = out_path.read_text(encoding="utf-8")
            self.assertIn("; Generated by fdm-slicer", content)
            self.assertIn("; LAYER:0", content)
            self.assertTrue("G2 " in content or "G3 " in content)


if __name__ == "__main__":
    unittest.main()
