from __future__ import annotations

import math
from pathlib import Path
from typing import Iterable

from .config import PrinterProfile
from .geometry import Coordinate, Layer
from .toolpath import Segment, Toolpath


class GCodeWriter:
    def __init__(self, printer: PrinterProfile, line_width: float, layer_height: float) -> None:
        self.printer = printer
        self.line_width = line_width
        self.layer_height = layer_height
        self.lines: list[str] = []
        self.e_position = 0.0
        self.current_xy: Coordinate | None = None
        self.current_z = 0.0

    def add(self, line: str) -> None:
        self.lines.append(line)

    def comment(self, text: str) -> None:
        self.lines.append(f"; {text}")

    def write_header(self) -> None:
        self.add("; Generated by fdm-slicer")
        self.add("G21 ; millimeters")
        self.add("G90 ; absolute positioning")
        self.add("M82 ; absolute extrusion")
        self.add(f"M104 S{self.printer.nozzle_temperature}")
        self.add(f"M140 S{self.printer.bed_temperature}")
        self.add("G28")
        self.add(f"M109 S{self.printer.nozzle_temperature}")
        self.add(f"M190 S{self.printer.bed_temperature}")
        self.add("G92 E0")
        self.add("G1 Z5 F3000")
        self.add(f"G1 X{self.printer.center_x - 50:.3f} Y10.000 F6000")
        self.add("G1 Z0.280 F1200")
        self.add(f"G1 X{self.printer.center_x + 50:.3f} E8 F900")
        self.add("G1 Y10.600 F6000")
        self.add(f"G1 X{self.printer.center_x - 50:.3f} E16 F900")
        self.add("G92 E0")
        self.add(f"M106 S{self.printer.fan_speed}")

    def write_footer(self) -> None:
        self.add("G92 E0")
        self.add("G1 E-1.0 F1800")
        self.add("G1 Z10 F3000")
        self.add(f"G1 X0 Y{self.printer.bed_depth:.0f} F6000")
        self.add("M104 S0")
        self.add("M140 S0")
        self.add("M107")
        self.add("M84")

    def travel_to(self, point: Coordinate, z: float | None = None) -> None:
        x, y = point
        parts = ["G0", f"X{x:.3f}", f"Y{y:.3f}"]
        if z is not None and abs(z - self.current_z) > 1e-9:
            parts.append(f"Z{z:.3f}")
            self.current_z = z
        parts.append(f"F{self.printer.travel_speed:.0f}")
        self.add(" ".join(parts))
        self.current_xy = point

    def extrusion_for_length(self, length: float) -> float:
        filament_area = math.pi * (self.printer.filament_diameter / 2.0) ** 2
        bead_area = self.line_width * self.layer_height
        return bead_area * length * self.printer.extrusion_multiplier / filament_area

    def line_to(self, point: Coordinate, z: float, speed: float) -> None:
        if self.current_xy is None:
            self.travel_to(point, z)
            return
        if abs(z - self.current_z) > 1e-9:
            self.add(f"G1 Z{z:.3f} F{self.printer.travel_speed:.0f}")
            self.current_z = z
        distance = math.dist(self.current_xy, point)
        if distance <= 1e-9:
            return
        self.e_position += self.extrusion_for_length(distance)
        self.add(f"G1 X{point[0]:.3f} Y{point[1]:.3f} E{self.e_position:.5f} F{speed:.0f}")
        self.current_xy = point

    def arc_to(self, segment: Segment, z: float, speed: float) -> None:
        if self.current_xy is None or segment.center_offset is None:
            self.line_to(segment.end, z, speed)
            return
        if abs(z - self.current_z) > 1e-9:
            self.add(f"G1 Z{z:.3f} F{self.printer.travel_speed:.0f}")
            self.current_z = z
        center = (
            self.current_xy[0] + segment.center_offset[0],
            self.current_xy[1] + segment.center_offset[1],
        )
        radius = math.dist(self.current_xy, center)
        start_angle = math.atan2(self.current_xy[1] - center[1], self.current_xy[0] - center[0])
        end_angle = math.atan2(segment.end[1] - center[1], segment.end[0] - center[0])
        if segment.clockwise:
            delta = (start_angle - end_angle) % (2.0 * math.pi)
            code = "G2"
        else:
            delta = (end_angle - start_angle) % (2.0 * math.pi)
            code = "G3"
        if delta <= 1e-6 or radius <= 1e-6:
            self.line_to(segment.end, z, speed)
            return
        self.e_position += self.extrusion_for_length(radius * delta)
        self.add(
            f"{code} X{segment.end[0]:.3f} Y{segment.end[1]:.3f} "
            f"I{segment.center_offset[0]:.3f} J{segment.center_offset[1]:.3f} "
            f"E{self.e_position:.5f} F{speed:.0f}"
        )
        self.current_xy = segment.end

    def write_toolpath(self, toolpath: Toolpath, z: float, speed: float) -> None:
        self.travel_to(toolpath.start, z)
        for segment in toolpath.segments:
            if segment.kind == "arc":
                self.arc_to(segment, z, speed)
            else:
                self.line_to(segment.end, z, speed)

    def save(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("\n".join(self.lines) + "\n", encoding="utf-8")
